class MathExample{
public static void main(String args[]){
System.out.println(Math.abs(-12123));
System.out.println(Math.cbrt(27));
System.out.println(Math.sqrt(25));
System.out.println(Math.signum(15));
System.out.println(Math.rint(1.4));
System.out.println(Math.ceil(-0.87));
System.out.println(Math.floor(1.25));
System.out.println(Math.random());
System.out.println(Math.pow(5,2));
System.out.println(Math.max(23,-22));
System.out.println(Math.min(25,30));
System.out.println(Math.copySign(5,-3));
System.out.println(Math.exp(2));
System.out.println(Math.expm1(2));
System.out.println(Math.getExponent(1234.5678));
System.out.println(Math.hypot(2,3));
System.out.println(Math.IEEEremainder(10,10));
System.out.println(Math.nextAfter(2,5));
System.out.println(Math.nextUp(2));
System.out.println(Math.round(23.6));
System.out.println(Math.acos(-1));
System.out.println(Math.asin(-1));
System.out.println(Math.atan(-1));
System.out.println(Math.atan2(1,2.5));
System.out.println(Math.cos(1));
System.out.println(Math.cosh(1));
System.out.println(Math.log(10));
System.out.println(Math.log10(10));
System.out.println(Math.log1p(10));
System.out.println(Math.sin(0.2));
System.out.println(Math.sinh(2.5));
System.out.println(Math.tan(2.5));
System.out.println(Math.tanh(2.5));
System.out.println(Math.toDegrees(Math.PI/4));
System.out.println(Math.toRadians(45));
System.out.println(Math.ulp(2.5));
}
}